Gülsüm Simge Bozdoğan 
20170808027

9 Numpy

In [24]:
import numpy as np
import scipy.linalg as sl
import time
x = 200
m = 500
A = np.random.normal(0, 1, (x,m))
z = np.random.rand(m)
t = np.random.rand(m)
B = sl.toeplitz(z,t)
print(f"A: {A}")
print(f"B: {B}")

A: [[-7.38430733e-01 -1.17784446e+00  7.60600871e-01 ... -2.65029882e-01
  -7.53663828e-02 -1.96970349e-01]
 [-5.95682811e-01  2.85074443e-01  2.84806455e-01 ... -1.16936656e-01
  -5.58777081e-01 -1.11479147e+00]
 [ 7.06786837e-01 -9.55308159e-01 -1.04281103e-01 ...  6.39467987e-01
  -8.19657397e-02 -8.51725051e-02]
 ...
 [-1.71947129e+00 -1.01509549e+00 -3.32971806e-01 ... -4.89655201e-02
   6.16052432e-01 -2.74630235e-01]
 [-4.60581897e-01 -5.87063157e-01  8.20210146e-01 ...  9.52520189e-02
   1.97049608e-01 -9.41602598e-01]
 [-2.82223388e-05 -1.57868287e+00  2.35105249e+00 ...  7.53636902e-02
  -1.13065482e+00 -1.48503324e-01]]
B: [[0.78650518 0.18133372 0.91070412 ... 0.64581732 0.74300606 0.39362452]
 [0.68045189 0.78650518 0.18133372 ... 0.136309   0.64581732 0.74300606]
 [0.35284961 0.68045189 0.78650518 ... 0.84886071 0.136309   0.64581732]
 ...
 [0.60557597 0.23245325 0.97667928 ... 0.78650518 0.18133372 0.91070412]
 [0.68676132 0.60557597 0.23245325 ... 0.68045189 0.78650518 

9.1

In [25]:
print("A + A: ")
print(A + A)
print("AA^T: ")
print(np.dot(A, A.T))
print("A^TA: ")
print(np.dot(A.T, A))
print("AB: ")
print(np.dot(A, B))
def func1(A, B, Lambda):
    X = B - Lambda * (np.eye(m))
    Y = np.dot(A, X)
    return Y

print("A(B - λI): ")
print(func1(A, B, 3))

A + A: 
[[-1.47686147e+00 -2.35568891e+00  1.52120174e+00 ... -5.30059764e-01
  -1.50732766e-01 -3.93940698e-01]
 [-1.19136562e+00  5.70148886e-01  5.69612909e-01 ... -2.33873311e-01
  -1.11755416e+00 -2.22958294e+00]
 [ 1.41357367e+00 -1.91061632e+00 -2.08562205e-01 ...  1.27893597e+00
  -1.63931479e-01 -1.70345010e-01]
 ...
 [-3.43894257e+00 -2.03019098e+00 -6.65943612e-01 ... -9.79310403e-02
   1.23210486e+00 -5.49260469e-01]
 [-9.21163794e-01 -1.17412631e+00  1.64042029e+00 ...  1.90504038e-01
   3.94099216e-01 -1.88320520e+00]
 [-5.64446776e-05 -3.15736574e+00  4.70210497e+00 ...  1.50727380e-01
  -2.26130963e+00 -2.97006647e-01]]
AA^T: 
[[512.34994632 -43.23930395 -20.12067247 ...  14.57218256  17.31417513
  -22.20231221]
 [-43.23930395 470.56399949  -8.58065713 ... -45.90870463 -13.23827799
   -4.60708269]
 [-20.12067247  -8.58065713 496.58771175 ...  -1.38652908  19.54580696
  -34.75761503]
 ...
 [ 14.57218256 -45.90870463  -1.38652908 ... 510.21624106  54.42112341
  -38.526819

9.2

In [18]:
b = np.random.rand(500, 1)
print("x for Bx=b: ")
print(np.linalg.solve(B,b))

x for Bx=b: 
[[-0.53940354]
 [-0.06304135]
 [ 0.18993362]
 [-0.13085989]
 [-0.37366142]
 [ 0.23678377]
 [-0.18720397]
 [-0.02341495]
 [-0.41974797]
 [ 0.06545222]
 [-0.25185022]
 [-0.77033323]
 [ 0.39804671]
 [ 0.0172724 ]
 [ 0.09026292]
 [-0.20524102]
 [ 0.27200359]
 [-0.15916954]
 [-0.3538399 ]
 [-0.08543   ]
 [-0.21532593]
 [-0.19878381]
 [ 0.02791683]
 [-0.29993685]
 [-0.12726552]
 [-0.03660883]
 [-0.17612223]
 [-0.09679377]
 [-0.54621925]
 [-0.36689849]
 [ 0.14089685]
 [-0.20765291]
 [-0.37708418]
 [-0.03151174]
 [ 0.14530514]
 [-0.07762343]
 [-0.38326233]
 [ 0.21612431]
 [-0.02796333]
 [-0.34399634]
 [ 0.43552037]
 [ 0.05908657]
 [-0.32645215]
 [ 0.14593057]
 [-0.3130827 ]
 [ 0.05410792]
 [-0.03643257]
 [ 0.15113438]
 [-0.21381706]
 [ 0.19435269]
 [ 0.18999385]
 [ 0.0208717 ]
 [-0.38234632]
 [-0.2973644 ]
 [ 0.06697556]
 [-0.0099552 ]
 [ 0.00356386]
 [-0.25578014]
 [ 0.38830359]
 [ 0.10070789]
 [ 0.17446882]
 [-0.24611777]
 [ 0.54230821]
 [ 0.13964993]
 [-0.35270924]
 [ 0.3896060

9.4

In [11]:
import numpy as np
import scipy.linalg as sl
import time
Z = np.random.normal(3,1, (x, x))
a, b = np.linalg.eig(Z)
print("The largest eigenvalue: ")
print(a.max())
print("The eigenvector: ")
print(b)

The largest eigenvalue: 
(600.0315467244559+0j)
The eigenvector: 
[[ 0.07312911+0.j          0.05936962-0.02649203j  0.05936962+0.02649203j
  ...  0.13115055+0.j         -0.01010498-0.01457165j
  -0.01010498+0.01457165j]
 [ 0.0722529 +0.j          0.05263647+0.03464106j  0.05263647-0.03464106j
  ... -0.08505221+0.j         -0.03506237+0.01751611j
  -0.03506237-0.01751611j]
 [ 0.06935743+0.j         -0.0295924 +0.06982475j -0.0295924 -0.06982475j
  ...  0.02733561+0.j         -0.06881825-0.00362444j
  -0.06881825+0.00362444j]
 ...
 [ 0.0709091 +0.j          0.05446346+0.0509256j   0.05446346-0.0509256j
  ... -0.04928426+0.j         -0.09519048-0.00873723j
  -0.09519048+0.00873723j]
 [ 0.0705276 +0.j          0.00956189+0.09727691j  0.00956189-0.09727691j
  ... -0.00391353+0.j         -0.10160967-0.01021094j
  -0.10160967+0.01021094j]
 [ 0.06840077+0.j          0.12565679+0.02065602j  0.12565679-0.02065602j
  ... -0.04138712+0.j          0.02443235+0.00831294j
   0.02443235-0.00831294j]]

9.6

In [23]:
def nearist_neighbor_function(A, z):
    return A[np.argmin(np.abs(A-z))]
A = np.random.rand(500)
print(f"A: {A}")
u = 1
print("Nearist neighbor: ")
print(nearist_neighbor_function(A, u))

A: [0.37262163 0.98266915 0.56174496 0.99738867 0.80067958 0.81479767
 0.89045479 0.32351558 0.08212783 0.99932903 0.87931955 0.44001977
 0.84456686 0.82688838 0.68304032 0.42627726 0.52900196 0.16505308
 0.87825794 0.06390146 0.72970363 0.29963281 0.9449949  0.17510085
 0.15706003 0.04641945 0.63413065 0.12110685 0.48395152 0.64460294
 0.74526934 0.72903442 0.12689547 0.57920256 0.23337646 0.35190504
 0.60379301 0.94056484 0.16997381 0.53387155 0.7338539  0.73799357
 0.90409783 0.22835948 0.50866002 0.61873741 0.8159465  0.54882465
 0.42334684 0.25337796 0.3434739  0.13111518 0.57378586 0.45589987
 0.30109409 0.27690802 0.31418494 0.49091858 0.53207329 0.46859621
 0.93082607 0.34069911 0.11608659 0.51222931 0.97394423 0.37646974
 0.67622987 0.53218448 0.92581745 0.38597335 0.57061726 0.88533232
 0.54878575 0.71496923 0.79448779 0.67622399 0.2860493  0.95908159
 0.60378928 0.74771809 0.69919261 0.81935568 0.65094333 0.34713223
 0.52489337 0.91887233 0.1471529  0.34752396 0.09036919 0.1